"use strict";
exports.__esModule = true;
var Movie_1 = require("./Movie");
var MovieScreening_1 = require("./MovieScreening");
var MovieTicket_1 = require("./MovieTicket");
var Order_1 = require("./Order");
var TicketExportFormat_1 = require("./TicketExportFormat");
// let movie = new Movie("The Matrix");
// let screening = new MovieScreening(new Date(), 10, new Movie("The Matrix"));
// movie.addScreening(screening);
var order = new Order_1.Order(1, false);
// order.addSeatReservation(new MovieTicket(1, 1, false, screening));
// order.addSeatReservation(new MovieTicket(1, 2, false, screening));
// order.addSeatReservation(new MovieTicket(1, 3, true, screening));
// order.addSeatReservation(new MovieTicket(1, 4, true, screening));
// order.addSeatReservation(new MovieTicket(1, 5, true, screening));
var movie = new Movie_1.Movie("The Matrix 2");
var screening = new MovieScreening_1.MovieScreening(new Date(), 10, movie);
movie.addScreening(screening);
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 1, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 2, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 3, true, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 4, true, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 5, true, screening));
console.log(order.calculatePrice());
order["export"](TicketExportFormat_1.TicketExportFormat.JSON);
