"use strict";
exports.__esModule = true;
var Movie_1 = require("./Movie");
var MovieScreening_1 = require("./MovieScreening");
var MovieTicket_1 = require("./MovieTicket");
var Order_1 = require("./Order");
var moment_1 = require("moment");
var movie = new Movie_1.Movie("The Matrix");
var screening = new MovieScreening_1.MovieScreening((0, moment_1["default"])().day(0).toDate(), 10, movie);
movie.addScreening(screening);
var order = new Order_1.Order(1, false);
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 1, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 2, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 3, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 4, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 5, false, screening));
order.addSeatReservation(new MovieTicket_1.MovieTicket(1, 6, false, screening));
console.log(order.calculatePrice());
